language: c
sudo: true
dist: xenial

os:
  - osx

osx_image: xcode10.2  

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update > /dev/null;
        brew install fpc > /dev/null;
      fi
      
install:
  - ./build.sh
  
script:
  - ls
